config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for  :users, 
              :path => '', 
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                       :registrations => 'registrations'
              }

  resources :users, only: [:show]
  resources :jewels
  resources :photos

  resources :jewels do
      resources :reservations, only: [:create]
    end

    resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

    resources :jewels do
    resources :reviews, only: [:create, :destroy]
  end

get '/preload' => 'reservations#preload'
get '/preview' => 'reservations#preview'

get '/your_trips' => 'reservations#your_trips'
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
	belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, scope: :recipient_id

	scope :involving, -> (user) do
		where("conversations.sender_id = ? OR conversations.recipient_id = ?", user.id, user.id)
	end

	scope :between, -> (sender_id, recipient_id) do
		where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", 
					sender_id, recipient_id, recipient_id, sender_id)
	end

end

app/views/conversations/index.html.erb
<div class="row">
	<div class="col-md-12">
		
		<div class="panel panel-default">
			<div class="panel-heading">Your conversations</div>
			<div class="panel-body">
				<div class="container">
					<% @conversations.each do |conversation| %>
						<% other = conversation.sender == current_user ? conversation.recipient : conversation.sender %>

						<%= link_to conversation_messages_path(conversation) do %>

							<div class="row conversation">
								<div class="col-md-2">
									<%= image_tag avatar_url(other), class: "img-circle avatar-medium" %>
								</div>
								<div class="col-md-2">
									<%= other.fullname %><br>
									<%= conversation.messages.last.message_time %>
								</div>
								<div class="col-md-8">
									<%= conversation.messages.last.content %>
								</div>
							</div>

						<% end %>
					<% end %>
				</div>
			</div>
		</div>
		
	</div>
</div>